### ISSUE TITLE
Performance du bouton donner une cenne à améliorer

### ISSUE THREAD

**Issue by CerebrumQc** [quaribou/Tokebac#10]
Lorsqu'on pèse en malade sur le harfang, le serveur semble planter à un certain moment et ça cesse de donner des cennes.
Il faut pouvoir : 

1. Peser sur le harfang en malade autant qu'on veut 
2. Laisser son doigt appuyer sur le harfang pour donner des cennes (plus on tient longtemps son doigt, plus le nombre de cennes s'accélère - exponentiel jusqu'à (1$-100 Q$) seconde max)

![Capture d’écran, le 2023-07-29 à 09 14 13](https://github.com/quaribou/Tokebac/assets/140896126/ce4bfba2-b540-4d2f-8b06-d78fa753f257)

**Comment by philbourg** [comment]
J'ajouterais le son aussi. Un mp3 de très faible qualité (qualité 8 bits). Ça peut être une format audio encore plus basse qualité si possible, il faut que ça load en un rien de temps.

**Comment by philbourg** [comment]
Svp changer le message de la notification par "Wôhò, pèse un peu moins vite, les serveurs chauffent!"
