### ISSUE TITLE
Créer formulaire d'inscription artiste

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#101]
Créer un Google forms avec les infos dont on a besoin :  

- Nom du projet 
- Courriel 
- Lien vers production audio 
- Lien vers dossier ou articles de presse 
- Lien vers événement ou show déjà fait

**Comment by philbourg** [comment]
Je crois que ce serait mieux directement dans Brevo, notre plateforme de mailing list

**Comment by ragamache** [comment]
Est-ce toujours d'actualité de le créer dans Brevo ou bien je le fais dans Google Form?

**Comment by philbourg** [comment]
https://linktr.ee/tokebac
