### ISSUE TITLE
Invitation compte admin

### ISSUE THREAD

**Issue by Swag495** [quaribou/Tokebac#11]
On a essayé d’ajouter [swag@tokebac.com] comme admin. L’invitation a été envoyée par mail mais lorsque j’ai essayé de faire mon compte, “Vous n’êtes pas invité”. L’adresse ne figure pas dans la liste d’admin dans le panneau admin.

**Comment by philbourg** [comment]
On va le mettre dans le Prioritaires, question que ça nous arrive pas lorsqu'on va commencer à inviter du monde.

**Comment by philbourg** [comment]
Malgré que c'est le compte Admin et qu'on a réussi à t'en donner une avec un autre e-mail. C'est les comptes Artistes qui sont prioritaires, et eux autres fonctionnement jusqu'à maintenant. Je vais déplacer dans Nouveautés.

**Comment by philbourg** [comment]
Dans Carnet de commandes plutôt.

**Comment by philbourg** [comment]
L'invitation mène toujours sur Vercel. 

![Image](https://github.com/quaribou/Tokebac/assets/67874414/ac09bf05-6b2e-4884-9166-26d202835405)

**Comment by jstrategiaAdmin** [comment]
@philbourg C'est fixé
