### ISSUE TITLE
Bug rare swipe droit

### ISSUE THREAD

**Issue by Swag495** [quaribou/Tokebac#12]
Message d'erreur en swippant à droite sur un de mes contenu dans le fil pour voir mon profil:

Application error: a client-side exception has occurred (see the browser console for more information).

C'est arrivé juste une fois

**Comment by philbourg** [comment]
Je l'ai ajouté aux Nouveautés. On verra si ça se reproduit.

**Comment by jstrategiaAdmin** [comment]
C'est réglé. Relié au crédit undefined.
