### ISSUE TITLE
Ajouter les Collections (le profil utilisateur)

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#13]
Ajouter Le profil utilisateur tel que prévu dans les maquettes, soit le Nom d'utilisateur en haut suivi des Contenus sociofinancés par ordre de Q$ donnés par Contenu sociofinancé.

**Comment by jstrategiaAdmin** [comment]
@philbourg C'est fait. Ce sera mergé mercredi

**Comment by philbourg** [comment]
Salut @jstrategiaAdmin , est-ce que le merge a été fait, ça me déconnecte toujours si j'appuie sur Profil.

**Comment by jstrategiaAdmin** [comment]
Le merge à pas encore été fait. Tu auras accès à la version prod Lundi
