### ISSUE TITLE
Corriger les profils d'artistes qui ne fonctionnent pas

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#14]
J'ai créé deux profils d'ARTISTE (Évilve Vedette et Cérebrum). Je peux créer du CONTENU, mais je ne peux swipé droite pour voir le PROFIL de l'ARTISTE. On voit plutôt une erreur disant que le profil n'existe pas. 

Je suspecte que c'est parce que j'ai mis des "é" dans le nom d'utilisateur, vous pouvez checker ça? 

![Image](https://user-images.githubusercontent.com/67874414/257018686-8789fb1d-6401-42ba-b99d-cee92c8bb3d3.png)

**Comment by LePhilBourg** [comment]
Quaribou a essayé d'effacer le compte Artiste de Evil et ensuite de le re-créer et ça ne fonctionne pas (evil@quaribou.net). 
Evil recoit un courriel, mais on ne voit pas son courriel apparaître dans le panneau ADMIN.

**Comment by LePhilBourg** [comment]
Je n'arrive pas non plus à voir mon compte (contact@philbourg.ca) dans la plateforme. 

J'arrive à créer des CONTENUS, mais lorsque je swipe droit, j'ai l'erreur suivante : 



![Image](https://github.com/quaribou/Tokebac/assets/141033679/4ade8941-4d54-4058-a12b-89a0e883caa2)


À corriger, il faut que l'ajout et les PROFIL d'ARTISTE fonctionnent sur la coche avant d'inviter nos premiers beta utilisateurs.

**Comment by philbourg** [comment]
![Image](https://github.com/quaribou/Tokebac/assets/67874414/f3858745-9d91-4918-8e74-34fcfe04ecc6)

**Comment by jstrategiaAdmin** [comment]
@philbourg Tout est régler et le merge sera fait aujourd'hui

**Comment by philbourg** [comment]
@jstrategiaAdmin 
Je n'arrive toujours pas à ajouter Évilve Vedette avec le courriel evil@quaribou.net

**Comment by jstrategiaAdmin** [comment]
Nous sommes en train de faire mise A jour de tous les environnements avec tous les maj. On fera un autre test après.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jstrategiaAdmin** [comment]
@philbourg nous avons redémarré la Bd à Zero. Tu devrais être en mesure d'inviter les comptes.

**Comment by philbourg** [comment]
Ç a fonctionne pour Evil@quaribou.net, mais â dirige vers VERCEL, j'ai créé un autre bogue pour ça (#43)
