### ISSUE TITLE
Faire avancement les paiements

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#15]
Je vais m'occuper de créer le compte Paypal entreprise de Quaribou. 
Je vais m'occuper de créer le modèle économique de la plateforme dans Miro. 
Je vais tenter de faire un suivi avec Léa une fois que j'aurai fait le tout.

**Comment by philbourg** [comment]
Quelques premiers détails :
- 1 cenne canadienne = 1 Quaribou dollars = 1 Q$
- J'ai éliminé le frais de serveurs, on va simplement percevoir 15% de "frais pour entretien et amélioration de la plateforme"
- Le frais de transaction Paypal (0.30$) doit être ajouté au montant de la charge. Donc, ce sera 5.30$ le total de la facture. 
- En fait, même chose pour le frais de 15%. Le monde sont habitué de payer des taxes, alors on va faire ça comme ça : si on fait une charge de X, on a une facture de (X/0.85)+0.30$. Donc, par exemple, pour donner 5$ aux artistes, ça coûte 88 cennes pour l'entretien de la plateforme et 30 cennes de frais de transaction pour un total de 6.18$ canadien pour 500 Q$. 
-Lorsqu'un paiement est fait, tout l'argent sans va dans le compte Paypal de Quaribou. 
-Lorsqu'un artiste veut retirer des Q$, il doit le faire par tranche de 50$. 
-Lorsqu'un artiste fait un retrait, un frais de 0.30$ est ajouté pour la transaction Paypal. 
- lorsqu'un artiste fait un retrait, le montant est retiré du compte Quaribou et transféré au compte Paypal de l'artiste
- À une période fixe à déterminer (par exemple chaque mois ou au trois mois), Stratejia va remettre une facture à Quaribou Culture avec le montant des frais de serveurs et autres services payants utilisé par la plateforme avec la mention inscrit "payé"
- les frais de serveurs et autres services seront perçu du compte Quaribou Culture au même moment que l'émission de la facture

Important: si les paiements automatiques (autant pour les artistes que pour le paiement de Stratejia) est compliqué, on passe pas de temps là dessus pour l'instant. Si c'est compliqué, on met en place un autre système (courriel + on ajoute une colonne pour les demandes de paiement dans le panneau admin) et Quaribou fera les paiements manuellement au début de chaque mois. 

L'important, c'est que les artistes et les utilisatrices puissent entrer leur Paypal, faire des recharges pour obtenir des Q$, que les paiements se virent dans le compte de Quaribou et quon est un moyen de savoir quel artiste veut faire un retrait. C'est ça le PMV des paiements (avec le calcul des frais).

**Comment by philbourg** [comment]
Oublier les paiements automatiques aux artistes. Oublier même le paiement aux artistes tout court pour l'instant, on va seulement faire la paiement du public en respectant les règles définies dans le commentaire précédent. 

Donc, je répète, on fait seulement le paiement du public, tout le reste est depriorisé pour se concentrer sur les autres Issues de la colonne Prioritaires. 

Ensuite, on va faire le Carnet de commandes et sil reste du temps, on fera avancer soit les idées soit le paiement automatique des artistes.  

p.s. on fera le transfert aux artistes manuellement au départ et l'artiste nous fera une demande par courriel.

**Comment by jstrategiaAdmin** [comment]
@philbourg on aimerait valider avec toi et valider le retrait des credit gratuit à la création d'un Lundi

**Comment by philbourg** [comment]
On va garder 1000 crédits gratuits pour l'inscription des nouveaux artistes. Je vais injecter 2000$ sur le compte Paypal de Quaribou pour offrir 10$ (1000 crédits) aux 200 premiers artistes qui vont s'inscrire sur la plateforme. 


Après discussion, on va faire un PMV du paiement pour que les artistes puissent faire une demande de paiement à Quaribou qui enverra l'adresse du compte Paypal et qui s'occupera de faire baisser les crédits aux artistes en même temps dans la plateforme. 

Plus tard on automatisera plus le tout.
