### ISSUE TITLE
Le lien unique ne fonctionne pas

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#16]
Lorsqu'on partage un lien unique, ça demande de se connecter en boucle même si la connexion est active (si on pèse sur CONTENU, ça fonctionne). 

![Image](https://user-images.githubusercontent.com/67874414/257018861-3e457db5-a9ea-40df-8e60-6a04690f1172.png)

**Comment by jstrategiaAdmin** [comment]
@philbourg: Nous ne sommes pas en mesure de reproduire le problème. Est-ce que tu as plus de détail?

https://tokebac-dev.vercel.app/Tokebac

**Comment by philbourg** [comment]
Je viens de vérifier, en fait, ça fonctionne avec collant le lien ou en partageant, mais ça marche pas dans Messenger sur Facebook. 

Peut être vérifier rapidement pourquoi ça bogue dans Messenger, mais si c'est compliqué, on passe, parce Facebook, c'est de la chenoutte de toute façon ;) 

Merci!
