### ISSUE TITLE
Donner les accès au code à Philippe Bourque

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#24]
Donner les accès ADMIN pour modifier l'ensemble du code, les courriels et toute autre système (bases de données, serveurs, etc.) à @philbourg dans le but de préparer la transition du PMV en production.

**Comment by jstrategiaAdmin** [comment]
@philbourg Toma s'en charge à l'instant

**Comment by philbourg** [comment]
J'ai accès merci.
