### ISSUE TITLE
Qu'arrive-t-il aux contenus si on efface un artiste?

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#27]
Si on efface un artiste, qu'est-ce qui arrive au contenu?
Est-ce qu'il est effacé de la base de données ou mis dans une corbeille quelconque? 

![Image](https://user-images.githubusercontent.com/67874414/258164174-40fee0ef-a1e2-4031-b277-73478504071b.png)

**Comment by jstrategiaAdmin** [comment]
Le contenu reste dans la bd, mais plus possible de visualiser

**Comment by philbourg** [comment]
C'est parfait!! 

Si on ouvre de nouveau avec le même user et courriel, est-ce que le contenu revient en ligne?

**Comment by philbourg** [comment]
On a discuté de ce point. Pour l'instant, si on efface un artiste, tout son contenu est effacé à jamais. 

Aussi, l'artiste perd ses crédits qui sont remis à la communauté pour entretenir et améliorer la plateforme. 

Ainsi, une artiste doit y penser un peu avant de publier, parce qu'un exile de la plateforme égale pour l'instant un "cancel" total. 

À terme, on trouvera un moyen de mettre une artiste sur pause sans la canceller. Pour la version bêta, ça sera ça. 

Il faut ajouter ces enjeux dans termes et conditions. 

Aussi, il faut ajouter une section si on cancel une artiste pour expliquer la décision. Le tout doit être transparent. 

Je déplace la carte dans le Groupe Gouvernance.

**Comment by jstrategiaAdmin** [comment]
parfait!
________________________________
De : Phil Bourg ***@***.***>
Envoyé : 9 août 2023 08:04
À : quaribou/Tokebac ***@***.***>
Cc : Pascal Girard ***@***.***>; Comment ***@***.***>
Objet : Re: [quaribou/Tokebac] Qu'arrive-t-il aux contenus si on efface un artiste? (Issue #27)


On a discuté de ce point. Pour l'instant, si on efface un artiste, tout son contenu est effacé à jamais.

Aussi, l'artiste perd ses crédits qui sont remis à la communauté pour entretenir et améliorer la plateforme.

Ainsi, une artiste doit y penser un peu avant de publier, parce qu'un exile de la plateforme égale pour l'instant un "cancel" total.

À terme, on trouvera un moyen de mettre une artiste sur pause sans la canceller. Pour la version bêta, ça sera ça.

Il faut ajouter ces enjeux dans termes et conditions.

Aussi, il faut ajouter une section si on cancel une artiste pour expliquer la décision. Le tout doit être transparent.

Je déplace la carte dans le Groupe Gouvernance.
