### ISSUE TITLE
Le système de crédits ne redonnent pas de crédits aux artistes producteurs de contenus

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#31]
En tant qu'artiste, je ne reçois aucun crédit lorsqu'un autre utilisateur me donne des crédits.
Il faut que lorsqu'un contenu reçoit des crédits, l'artiste reçoivent ses crédits :) 

Merci,

**Comment by jstrategiaAdmin** [comment]
C'est en PR

Question: Est-ce que un artiste peut redonner les crédit qu'il a reçu + ceux qu'il a acheté? Comme un compte banque centralisé.

**Comment by philbourg** [comment]
Oui, l'artiste peut redonner les crédits qu'il reçoit, comme un compte bancaire :). 

Tout crédit qu'il reçoit doit pouvoir être utilisé. 

(Éventuellement, un jour, l'artiste pourra même être rémunéré avec la plateforme et utiliser la plateforme pour payer des services).
