### ISSUE TITLE
L'aperçu lorsqu'on partage un lien unique n'a pas la bonne image

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#32]
![Image](https://user-images.githubusercontent.com/67874414/258167502-14a352c8-2aeb-4fe7-b078-c02e6b16e372.png)

**Comment by jstrategiaAdmin** [comment]
@philbourg  C'est fait maintenant c,est le harfang. Sera mergé pour lundi

**Comment by philbourg** [comment]
De mon côté, c'est le Sablier maintenant. 



![Image](https://github.com/quaribou/Tokebac/assets/67874414/2ecd487f-7246-4de9-ab9d-354ca83bff55)
