### ISSUE TITLE
Courriel d'invitation d'un artiste à corriger

### ISSUE THREAD

**Issue by tokebacRD** [quaribou/Tokebac#4]
1. L'adresse de provenance est tgagne@stratejia.ca, il faudrait qu'il vienne de info@tokebac.com. 
2. Le message devrait être le suivant : https://miro.com/app/board/uXjVOt0sOpQ=/?moveToWidget=3458764556437212898&cot=14
3. Tokebac ne prend pas de é 
4. Lorsqu'on clique sur Créer mon compte, ça devrait se diriger directement sur connexion afin d'éviter un clique supplémentaire.

**Comment by jstrategiaAdmin** [comment]
C'est fait
