### ISSUE TITLE
Parcours profil qui déconnecte à corriger 

### ISSUE THREAD

**Issue by philbourg** [quaribou/Tokebac#41]
Voici un parcours à corriger

1-Aller sur son profil
2-Choisir et ouvrir un contenu
3-Cliquer de nouveau sur profil 

En ce moment, le parcours déconnecte. 
Il faut que ce parcours ramène sur le profil, c'est le parcours que je fais sans faire exprès sans arrêt, car je veux retourner àa Collection lorsque j'ai un contenu. 

Merci!

@jstrategiaAdmin

**Comment by jstrategiaAdmin** [comment]
@philbourg C'est faite dit Léa
