### ISSUE TITLE
Création de contenu - Pas de limite minimum pour créer un contenu

### ISSUE THREAD

**Issue by CerebrumQc** [quaribou/Tokebac#6]
Enlever la limite minimum pour créer un contenu. 
Même pas un caractère. 
Si quelqu'un veut juste posrter une photo, c'est son choix. 

![Capture d’écran, le 2023-07-29 à 08 43 57](https://github.com/quaribou/Tokebac/assets/140896126/90432a5f-e982-4086-9e3f-7dab28b141a2)

**Comment by jstrategiaAdmin** [comment]
@philbourg Sera ajuster pour la démo de lundi
