### ISSUE TITLE
Les icônes ne sont pas les bons 

### ISSUE THREAD

**Issue by CerebrumQc** [quaribou/Tokebac#8]
Icônes actuels : 

![Capture d’écran, le 2023-07-29 à 08 50 20](https://github.com/quaribou/Tokebac/assets/140896126/dee14e0e-e9cf-4882-b64c-15e3bbf0683a)

1. On veut un icône d'aléatoire, pas un infini. 
2. On veut un icône de Alien8Bits, pas un profil (ça mène vers notre Collection, pas notre Profil)
3. On veut une forme trois dimensions comme si c'est un bouton 

Voici les maquettes, mais il faut que les boutons Aléatoires et Collection soient en noir fond bleu au lieu de en blanc fond bleu.

![Capture d’écran, le 2023-07-29 à 08 51 07](https://github.com/quaribou/Tokebac/assets/140896126/77848ff5-2413-4574-adf1-333b38a36191)

**Comment by jstrategiaAdmin** [comment]
@philbourg  As-tu les svg dans bon icone?

**Comment by philbourg** [comment]
Nope. Le harfang est en PNG et les autres je les aies fait dans Miro. 

Je peux sûrement te convertir le harfang dans affinity designer. Je peux voir aussi ce que je peux faire pour les autres. 

Si vous préférez juste en inventer de nouveau (sauf le harfang), faites-moi signe, c'est comme vous voulez.

**Comment by philbourg** [comment]
https://github.com/quaribou/Tokebac/blob/main/Images/Tokebac_logo.svg

(pas sur pentoute de ce que ça donne, tu me diras)

**Comment by philbourg** [comment]
On garde ça de même pour l'instant, c'est ben bon!
