### ISSUE TITLE
Swipe droit vers le profil artiste trop lent

### ISSUE THREAD

**Issue by CerebrumQc** [quaribou/Tokebac#9]
Lorsqu'on clique pour aller voir le profil artiste (ou swipe), c'est lent, il faut que ça clenche plus que ça. 
Si c'est pas possible, ajouter une animation pour faire patienter le cerveau. 

Animation : voir la page précédente pour comprendre que ça bouge dans l'interface ou ajouter de quoi de cool. À voir avec le UX.

**Comment by jstrategiaAdmin** [comment]
@philbourg nous allons travailler sur un feedback pour le client sur le loading et accélérer la transition

**Comment by philbourg** [comment]
C'est le rendering la première fois qu'on vouvre un profil artiste que ça fait ça.  On va ben vivre avec pour l'instant.
